config/routes.rb
Rails.application.routes.draw do
  get 'events/add' => 'events#add', as: 'add_event'
  get 'events/list' => 'events#list', as: 'list_events'
  get 'event/:id' => 'events#show', as: 'show_event'

  get 'user/signin' => 'sessions#new'
  post 'user/signin' => 'sessions#create'

  get 'user/logout' => 'sessions#destroy'

  get 'user/signup' => 'users#new'
  post 'user/signup' => 'users#create'

  get '~:user_name'  => 'users#show', as: 'user_profile'
  get 'user/profile/edit' => 'users#profile', as: 'edit_user_profile'
  post 'user/profile/edit' => 'users#profile'

  get 'user/password/new' => 'users#reset_password_new'
  post 'user/password/new' => 'users#reset_password_new', as: 'user_reset_password_new'
  get 'user/password/edit' => 'users#reset_password_change'
  post 'user/password/edit' => 'users#reset_password_change', as: 'user_reset_password_change'

  get 'user/email/confirm/send' => 'users#confirm_email_send'
  get 'user/email/confirm' => 'users#confirm_email'

  root 'home#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'terms' => 'home#terms'
  get 'privacy' => 'home#privacy'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action  :require_login

  def index
    @home = "Home page #{session[:user_id]}, #{session[:user_name]}"
  end

  def about
  end

  def contact
  end

  def terms
  end

  def privacy
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h1>Home#about</h1>

<p>关于我们</p>

app/views/home/contact.html.erb
<h1>Home#contact</h1>

<p>联系我们</p>

app/views/home/index.html.erb
<h1>Home#index</h1>

<% if logged_in? %>
    <p><%= @home %> Welcome, <%= current_user.user_name %></p>
<% end %>

<% if logged_in? %>
    <%= link_to 'Edit Profile', edit_user_profile_path %><br>
    <%= link_to 'User Page', user_profile_path(current_user.user_name) %><br>
    <%= link_to "验证邮箱", user_email_confirm_send_path %><br>
    <%= link_to "Log out", user_logout_path %><br>
<% else %>
    <%= link_to "Sign in", user_signin_path %><br>
    <%= link_to "Sign up", user_signup_path %><br>
<% end %>

app/views/home/privacy.html.erb
<h1>Home#privacy</h1>

<p>隐私政策</p>

app/views/home/terms.html.erb
<h1>Home#terms</h1>

<p>服务条款</p>