config/routes.rb
Rails.application.routes.draw do
  get 'events/add' => 'events#add', as: 'add_event'
  get 'events/list' => 'events#list', as: 'list_events'
  get 'event/:id' => 'events#show', as: 'show_event'

  get 'user/signin' => 'sessions#new'
  post 'user/signin' => 'sessions#create'

  get 'user/logout' => 'sessions#destroy'

  get 'user/signup' => 'users#new'
  post 'user/signup' => 'users#create'

  get '~:user_name'  => 'users#show', as: 'user_profile'
  get 'user/profile/edit' => 'users#profile', as: 'edit_user_profile'
  post 'user/profile/edit' => 'users#profile'

  get 'user/password/new' => 'users#reset_password_new'
  post 'user/password/new' => 'users#reset_password_new', as: 'user_reset_password_new'
  get 'user/password/edit' => 'users#reset_password_change'
  post 'user/password/edit' => 'users#reset_password_change', as: 'user_reset_password_change'

  get 'user/email/confirm/send' => 'users#confirm_email_send'
  get 'user/email/confirm' => 'users#confirm_email'

  root 'home#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'terms' => 'home#terms'
  get 'privacy' => 'home#privacy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Huo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= link_to '首页', root_path %>
    <%= link_to '发起活动', add_event_path %>

<%= yield %>

</body>
</html>